### ISSUE TITLE
Any description on the json configuration?

### ISSUE THREAD

**Issue by suguanyi** [Watchful1/PushshiftDumps#17]
Thanks for sharing the data and the scripts, that's really helpful!
Can you share the description or the codebook on the meaning of the jsons in the file? Although I have decompressed the zst, I cannot understand which are the contents of the posts.

**Comment by Watchful1** [comment]
I usually recommend PRAW's documentation for the list of fields

https://praw.readthedocs.io/en/latest/code_overview/models/submission.html

https://praw.readthedocs.io/en/latest/code_overview/models/comment.html
