### ISSUE TITLE
Removal requests

### ISSUE THREAD

**Issue by JodanJodan** [Watchful1/PushshiftDumps#18]
Regarding your Academic Torrents dumps, could you implement a user removal system similar to [Pushshift's](https://old.reddit.com/r/pushshift/comments/pat409/online_removal_request_form_for_removal_requests/) / [PullPush's](https://removals.pullpush.io/) / [Arctic Shift's](https://docs.google.com/forms/d/e/1FAIpQLSfzkmE8Bg6K_xii7aRm66ljzvo2tR59lTsdJ99acW4WX786Vw/viewform), for general privacy / CCPA / GDPR reasons?

**Comment by Watchful1** [comment]
It is not technically possible to remove data from torrent files.

**Comment by JodanJodan** [comment]
I meant before you publish future or updated torrents.
