### ISSUE TITLE
Understanding the memory requirements of combine_folder_multiprocess.py

### ISSUE THREAD

**Issue by Flopblopper** [Watchful1/PushshiftDumps#19]
While attempting to run through some of the Pushshift dumps using combine_folder_multiprocess.py, the script consumes all of my memory and is halted by the OOM killer. This occurs even if I set the --processes value to 2.

Is it possible to estimate the potential memory consumption required to run through any particular file in order to calculate the most efficient number of processes that should be used?

**Comment by Watchful1** [comment]
Unfortunately due to the compression level the larger files can use up to something like 2 gb of memory per process. I don't think there's an easy way to get a direct number, but it's a lot.
