### ISSUE TITLE
'utf-8' codec can't decode byte 0xe5 in position 134217727: unexpected end of data

### ISSUE THREAD

**Issue by refaat31** [Watchful1/PushshiftDumps#7]
came across this issue while trying to iterate over a .zst file (of Pushshift reddit dump) and convert it to .csv file, using the to_csv.py. what's the solution to this?

data dump to convert - RS_2022-05.zst
link to jupyter notebook containing the steps and log of the error encountered - https://colab.research.google.com/drive/1MPCHGFj97augj7CLHQrbhfAgvssU3UJS?usp=sharing

**Comment by Watchful1** [comment]
Should be fixed now, re-download the script and try again.

**Comment by ClaudiaShu** [comment]
Hi! I run into a similar issue with comments in dump [RC_2023-02.zst]:

```Exception has occurred: UnicodeDecodeError
'utf-8' codec can't decode bytes in position 16777214-16777215: unexpected end of data
  File "/disks/sdc/yuxuan/software/PushshiftDumps/scripts/iterate_folder.py", line 25, in read_lines_zst
    chunk = reader.read(2**24).decode()  # read a 16mb chunk at a time. There are some really big comments
  File "/disks/sdc/yuxuan/software/PushshiftDumps/scripts/iterate_folder.py", line 56, in <module>
    for line, file_bytes_processed in read_lines_zst(input_file[0]):
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 16777214-16777215: unexpected end of data```

Any idea how to solve this? Thanks!

**Comment by Watchful1** [comment]
I think I just didn't update the iterate_folder script when I did the other ones. Should work now.
