### ISSUE TITLE
Use of File in Academic Manuscript (DOI Request)

### ISSUE THREAD

**Issue by TYB25** [Watchful1/PushshiftDumps#8]
Hello Watchful1,

I am a student at the University of Pittsburgh and am conducting a study that would benefit from using your script to extract the data from the Pushshift archive files.

Could you generate a DOI for your work? This would allow me to cite your work in my paper correctly and give you recognition for your very well-designed script.

I have included a link to the instructions for creating a DOI below:
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content#issuing-a-persistent-identifier-for-your-repository-with-zenodo

Thank you,
TYB25

**Comment by Watchful1** [comment]
I've had a number of different researchers ask to cite me or my scripts, but I've never heard of needing a DOI. Could you explain why it would be necessary?

**Comment by TYB25** [comment]
A DOI through Zenodo will archive a copy of your repository, ensuring that other researchers have access to the exact version of your code used in a mine and others research projects. It will also archive your open-source license so that a publication company knows that your script was used with permission. 

I do not have much experience in this area, but the principal investigator I am working under said that many researchers do not correctly cite GitHub, leading to code disappearing and programmers not receiving proper credit for their scripts being used in academia.

Thank you again for considering my request.

**Comment by Watchful1** [comment]
Unfortunately it doesn't look like it would work for my repository. It creates copies of releases you make through github, which I don't use. You can see the [page here](https://github.com/Watchful1/PushshiftDumps/releases), there aren't any. It makes more sense for code projects that are large and have to be compiled to be used. Simple python scripts like this can just be used as is, there's no setup necessary.

If you want other researchers to be able to use the exact same code, I'd recommend just including a complete copy of it with your work. But I don't know that much about publishing papers.

**Comment by TYB25** [comment]
Using a repository address instead of a DOI should be okay; Could you create a CITATION.cff file for your software? I have linked to a CFF file generator and GitHub documentation below:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

https://citation-file-format.github.io/cff-initializer-javascript/#/

Thank you again for your help. I genuinely appreciate it.

**Comment by Watchful1** [comment]
Sure, added

**Comment by TYB25** [comment]
Thank you!
